### ISSUE TITLE
Worst Plugin out there

### ISSUE THREAD

**Issue by Kenner-G** [NetherTechnology/BedWars#10]
This is the most poorly written plugin I've ever seen, they probably never test the plugin, it doesn't work, so many syntax errors. Go get a job at McDonalds or something

HAVE YOU EVER TESTED YOUR OWN CRAP? IT'S TERRIBLE. YOU ARE PROBABLY A 9 YEAR OLD TRYING TO CODE.
---

**Comment by KitrosMC** [comment]
Most of the server in China can use this plugin, Maybe its your own problem???
