### ISSUE TITLE
Error.. 

### ISSUE THREAD

**Issue by alair069** [NetherTechnology/BedWars#7]
![28475415-7732d214-6e22-11e7-9226-1370155bca58](https://user-images.githubusercontent.com/27539870/28495551-6c9f6a92-6f26-11e7-9943-52ee647d8e69.png)

**Comment by KitrosMC** [comment]
fixed

**Comment by alair069** [comment]
01:02:01 [CRITICAL] Unhandled exception executing command 'bw shop' in Bedwars: Undefined variable: g
01:02:01 [CRITICAL] ErrorException: "Undefined variable: g" (EXCEPTION) in "/plugins/BedWars-master/src/Bluplayz/BedWars" at line 1514

Error spawning Villager
